name: domain_layer
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  #dependency injection
  injectable: ^2.1.1
  get_it: ^7.2.0

  #freezed
  freezed: ^2.3.2

  #code generate
  retrofit_generator: ^6.0.0+1
  injectable_generator: ^2.1.5
  json_serializable: ^6.6.1
  flutter_lints: ^2.0.0
  
  data_layer:
    path: ../data_layer
  

  #clean_annotation
  clean_annotation:
    path: ../../../clean_annotation/clean_annotation/

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.3.3

  #clean_annotation
  clean_annotation_generator:
    path: ../../../clean_annotation/clean_annotation_generator/

  




flutter:

 
  uses-material-design: true

